language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  apt:
    packages:
    - libgconf-2-4

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

cache:
  directories:
  - $HOME/.m2

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - mvn clean package -DskipTests -q

before_script:
  - docker cp ./target/*.xar exist-ci:exist/autodeploy/111.xar
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - mvn test
  # - npm run cypress -- --record

after_success:
  - docker ps
